<a href="https://colab.research.google.com/github/xileFFFFF/Junyi_Li-Programming-and-BigDataAnalytics-MSFT2627/blob/main/%E2%80%9CJunyi's%20homework%20of%202.01%20%E2%80%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://drive.google.com/uc?export=view&id=1vv_PsWBnUJwSCkwKDoJAC-vXjtaEA4Ts)

# Introduction to Pandas

### What is Pandas?
As Python has grown to become a popular solution for data analysis, many new tools have been introduced to support such tasks. Pandas is arguably the most popular and widely used of these, although it does have some limitations (if working with very large datasets you may want to look at Dask and/or PySpark).

First, we will import it into our session. We will also import numpy - another widely used Python package for working with numerical data (the name is a portmanteau of "numerical" and "python"). By convention we import pandas as "pd" and numpy as "np". This is equivalent to giving it a variable name.

In [ ]:
import pandas as pd
import numpy as np

### Testing our installation
To test everything is working we will create some fake data frame using numpy and load it into a pandas dataframe (more on these below). First we will create the random numbers:

In [ ]:
x = np.random.rand(10,1)
x

The commands here have told numpy to create a set of random numbers between zero and one. The arguments we have passed, "1" and "10", tells numpy we want a 10x1 array of numbers (i.e. a vector).

Next we will create a pandas dataframe using "x":

In [ ]:
testdf = pd.DataFrame(x)
testdf

We have now successfully created a pandas dataframe!

### What are Dataframes?
Pandas has a very elegant way of managing data, very much borrowed from the statistical language R, mostly based around dataframes. You can think of dataframes a bit like an Excel table with rows, columns and common operations like sum, average and so on. We can use this on top of our previous work on lists and dictionaries (etc.) more usable and malleable.

To begin with we will create a dataset - in this case a dictionary.

In [15]:
orders = {'o10001':{'date':'2025/01/10', 'product':'Blockchain database', 'quantity':'1'},
            'o10002':{'date':'2025/01/13', 'product':'Stock market prediction engine', 'quantity':'2'},
            'o10003':{'date':'2025/01/14', 'product':'Portfolio optimisation tool', 'quantity':'10'},
            'o10004':{'date':'2025/01/15', 'product':'Man\'s suit', 'quantity':'2'}
}
orders

{'o10001': {'date': '2025/01/10',
  'product': 'Blockchain database',
  'quantity': '1'},
 'o10002': {'date': '2025/01/13',
  'product': 'Stock market prediction engine',
  'quantity': '2'},
 'o10003': {'date': '2025/01/14',
  'product': 'Portfolio optimisation tool',
  'quantity': '10'},
 'o10004': {'date': '2025/01/15', 'product': "Man's suit", 'quantity': '2'}}

We can convert this to a Dataframe with great ease

In [ ]:
import pandas as pd
import numpy as np

orders_df = pd.DataFrame(orders)
orders_df

We can even create such outputs from more complex dictionaries, such as a dictionary which includes a nested list:

In [21]:
customers = {'Siamak':{'name':'Siamak Naderi', 'open_orders':3, 'orders':['o10001', 'o10002', 'o10004']},
             'Ram':{'name':'Ram Gopal', 'open_orders':0, 'orders':[]},
             'Moris':{'name':'Moris Strub', 'open_orders':1, 'orders':['o10003']},
             'Ephie':{'name':'Ephie Wang', 'open_orders':0, 'orders':[]}
}
customers

{'Siamak': {'name': 'Siamak Naderi',
  'open_orders': 3,
  'orders': ['o10001', 'o10002', 'o10004']},
 'Ram': {'name': 'Ram Gopal', 'open_orders': 0, 'orders': []},
 'Moris': {'name': 'Moris Strub', 'open_orders': 1, 'orders': ['o10003']},
 'Ephie': {'name': 'Ephie Wang', 'open_orders': 0, 'orders': []}}

In [22]:
customers_df = pd.DataFrame(customers)
customers_df

                               Siamak        Ram        Moris       Ephie
name                    Siamak Naderi  Ram Gopal  Moris Strub  Ephie Wang
open_orders                         3          0            1           0
orders       [o10001, o10002, o10004]         []     [o10003]          []

Pandas dataframes can also be built from various other data structures and sources (including Excel files, CSVs, text files, databases and many more). To conclude the session we will look at a list example:

In [ ]:
a = [1, 2, 3, 4]
b = ["a", "b", "c", "d"]
c = [True, False, True, False]

listdf = pd.DataFrame([a, b, c])
listdf

### EXERCISE
Try building you own dataframes from a list and/or dictionary you create. What would happen if you have an item missing from one element. E.g. if "c" in the above example only had three items - True, False, True - rather than four. Test it - does the output match your expectation?

Answer: Directly quoting the above data would result in "none" or error.

I am planning to build a database created by me for a second attempt.

This is the correct list：

In [20]:
import pandas as pd
import numpy as np

name = ['Felix','Jessica','Feliks','Zzz']
number = ['23','9','87','666']
choose = ['F','T','F','F']

listdf = pd.DataFrame([name,number,choose])
listdf

       0        1       2    3
0  Felix  Jessica  Feliks  Zzz
1     23        9      87  666
2      F        T       F    F

Lost one：

In [19]:
import pandas as pd
import numpy as np

name = ['Felix','Jessica','Feliks','Zzz']
number = ['23','9','87','666']
choose = ['F','T','F']

listdf = pd.DataFrame([name,number,choose])
listdf

       0        1       2     3
0  Felix  Jessica  Feliks   Zzz
1     23        9      87   666
2      F        T       F  None

The other answer is:

In [25]:
import pandas as pd
import numpy as np


orders_df = pd.DataFrame(orders)
orders_df

customers = {'Felix':{'name': 'Felix Lee','open_orders':6,'orders':['zZZ666','zZZ923','zZZ807','zZZ567','zZZ123','zZZ001']},
             'Jessica':{'name':'Jessica Zhao','open_orders':1,'orders':['zZZ888'] },
             'Feliks':{'name':'Feliks Li','open_orders':0,'orders':[]},
             'Zzz':{'name':'Zzz Beauty','open_orders':2,'orders':['zZZ135','zZZ999']}
}
customers_df = pd.DataFrame(customers)
customers_df

,Felix,Jessica,Feliks,Zzz
name,Felix Lee,Jessica Zhao,Feliks Li,Zzz Beauty
open_orders,6,1,0,2
orders,"[zZZ666, zZZ923, zZZ807, zZZ567, zZZ123, zZZ001]",[zZZ888],[],"[zZZ135, zZZ999]"

If lost some data:

In [26]:
import pandas as pd
import numpy as np


orders_df = pd.DataFrame(orders)
orders_df

customers = {'Felix':{'name': 'Felix Lee','open_orders':6,'orders':['zZZ666','zZZ923','zZZ807','zZZ567','zZZ123','zZZ001']},
             'Jessica':{'name':'Jessica Zhao','open_orders':1},
             'Feliks':{'name':'Feliks Li','orders':[]},
             'Zzz':{'name':'Zzz Beauty','open_orders':2,'orders':['zZZ135','zZZ999']}
}
customers_df = pd.DataFrame(customers)
customers_df

,Felix,Jessica,Feliks,Zzz
name,Felix Lee,Jessica Zhao,Feliks Li,Zzz Beauty
open_orders,6,1,NaN,2
orders,"[zZZ666, zZZ923, zZZ807, zZZ567, zZZ123, zZZ001]",NaN,[],"[zZZ135, zZZ999]"

and:

In [27]:

import pandas as pd
import numpy as np

customers = {
    'name': ['Felix Lee', 'Jessica Zhao', 'Feliks Li', 'Zzz Beauty'],
    'open_orders': [6, 1, 0, 2],
    'orders': [
        'zZZ666',
        'zZZ888',
        'zZZ567'
    ]
}

customers_df = pd.DataFrame(customers)

list(customers_df)

ValueError: All arrays must be of the same length

Therefore, I think that using dataframes will result in 'none', while using dictionary will lead to both 'none' and 'error' situations.
Because when using 'dictionary' to nest 'dataframes', if there is a missing part within it, an error will occur. However, if only the word 'dictionary' is used, then 'none' will appear.